apiVersion: batch/v1
kind: Job
metadata:
  name: dt-delivery-storage
  namespace: bia-ds-dev
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.lrl.lilly.com/compute: serverless
        app.kubernetes.io/name: ldo-nextflow-adhoc
    spec:
      serviceAccountName: bia-ds
      restartPolicy: Never    
      containers:
      - name: dt-delvry-storge-container
        image: 283234040926.dkr.ecr.us-east-2.amazonaws.com/dynamic_targeting:mlops_wip-sha-13dcea83be9a
        command: ["nextflow", "run", "dt-delivery-storage.nf", "-c", "/ldo/work/nextflow.config", "-profile", "prod_neutral"]
        # args: ["--pipeline", "optimize"] # suggestions, delivery,stack,decompose, constraints
        env:
          - name: NXF_WORK
            value: "/bia-ds-dt-ldo-data/work"
        volumeMounts:
        - name: bia-ds-dt-ldo-data
          mountPath: /bia-ds-dt-ldo-data/work
        - name: ldo-nextflow-configmap
          mountPath: /ldo/work  
      volumes:
      - name: bia-ds-dt-ldo-data
        persistentVolumeClaim:
          claimName: bia-ds-dt-ldo-data
      - name: ldo-nextflow-configmap
        configMap:
          name: ldo-nextflow-configmap
          items:
          - key: nextflow.config
            path: nextflow.config